services:
  server:
    build:
      context: .
      target: ${TARGET:-develop}
    image: ${IMAGE:-adobe-api}
    stdin_open: true
    tty: true
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@database/${DATABASE_NAME}?schema=public
      SELENIUM_SERVER: http://browser:4444/wd/hub
    volumes:
      - .:/app
  database:
    image: postgres:17.0
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - '8000:8080'
  browser:
    image: selenium/standalone-chrome:130.0
    restart: always
    ports:
      - 4444:4444
volumes:
  pgdata:
    driver: local
